name: sonobuoy
baseurl: /sonobuoy
google_analytics: FILL_OUT
latest: v0.10.0
versions:
- v0.10.0
- v0.9.0
- v0.8.0
versioning: false
logo: assets/img/logo.svg
exclude:
- gen_version.sh
- v0.10.0
- v0.9.0
- v0.8.0
plugins:
- jekyll-redirect-from
contact:
  google: https://groups.google.com/forum/#!forum/heptio-sonobuoy
  github: https://github.com/heptio/sonobuoy
  twitter: https://twitter.com/heptiosonobuoy
  slack: https://kubernetes.slack.com/messages/sonobuoy
defaults:
- scope:
    path: latest
  values:
    version: latest
    gh: https://github.com/heptio/sonobuoy/tree/master
- scope:
    path: v0.10.0
  values:
    version: v0.10.0
    gh: https://github.com/heptio/sonobuoy/tree/v0.10.0
- scope:
    path: v0.9.0
  values:
    version: v0.9.0
    gh: https://github.com/heptio/sonobuoy/tree/v0.9.0
- scope:
    path: v0.8.0
  values:
    version: v0.8.0
    gh: https://github.com/heptio/sonobuoy/tree/v0.8.0
